apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8-s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-k8-s
  template:
    metadata:
      labels:
        app: nestjs-k8-s
    spec:
      containers:
        - name: nestjs-k8-s
          image: td665/nestjs-k8-s
          ports:
            - containerPort: 3000
